name: openjk # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
base: core18
summary: Open Source port of the Jedi Knight and Jedi Outcast series # 79 char long summary
description: |
  OpenJK is an effort by the JACoders group to maintain and improve the game engines on which the Jedi Academy (JA) and Jedi Outcast (JO) games run on, while maintaining full backwards compatibility with the existing games. 
  This project does not attempt to rebalance or otherwise modify core gameplay.



grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
 LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
apps:
 openjk:
  command: desktop-launch $SNAP/JediAcademy/openjk.x86_64
  plugs:
  - alsa
  - pulseaudio
  - x11
  - opengl
  - network 
  - network-bind
  - desktop
  - desktop-legacy
  - wayland
  - unity7  
  
 openjkded:
  command: JediAcademy/openjkded.x86_64
  plugs:
  - alsa
  - pulseaudio
  - x11
  - opengl
  - network 
  - network-bind
  
 openjk-sp:
  command: desktop-launch $SNAP/JediAcademy/openjk_sp.x86_64
  plugs:
  - alsa
  - pulseaudio
  - x11
  - opengl
  - desktop
  - desktop-legacy
  - wayland
  - unity7

parts:
  openjk-bin:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/JACoders/OpenJK.git
    after: [desktop-glib-only]
    build-packages:
    - libjpeg8-dev 
    - libpng12-dev 
    - zlib1g-dev 
    - libsdl2-dev
    stage-packages:
    - libfreetype6
    - libglu1-mesa
    - libopenal1
    - libsdl2-2.0-0
    - libjpeg8
    - libpng16-16
    - zlib1g
    - libpulse0
