name: openjk # you probably want to 'snapcraft register <name>'
version: '1.0.1.1+git' # just for humans, typically '1.2+git' or '1.3.2'
icon: ./snap/gui/OpenJK_Icon_256.png
summary: Open Source port of the Jedi Knight and Jedi Outcast series # 79 char long summary
description: |
  OpenJK is an effort by the JACoders group to maintain and improve the game engines on which the Jedi Academy (JA) and Jedi Outcast (JO) games run on, while maintaining full backwards compatibility with the existing games. 
  This project does not attempt to rebalance or otherwise modify core gameplay.
  PLEASE NOTE: Original assets from Jedi Academy and Jedi Outcast (.pk3 files) are required to play.
  Place these files in "~/snap/openjk/.local/share/openjk/base",
  Or "~/snap/openjk/.local/share/openjo/base" respectively.

base: core20
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

environment:
 #LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio # Legacy
 SDL_AUDIODRIVER: pulse

apps:
 openjk:
  command: ./usr/local/JediAcademy/openjk
  extensions: [gnome-3-38] # Required to get Glib Graphics working, see: https://www.gitmemory.com/issue/ubuntu/snapcraft-desktop-helpers/216/693388492
  plugs:
  - audio-playback
  - alsa
  - pulseaudio
  - x11
  - opengl
  - network 
  - network-bind
  - desktop
  - desktop-legacy
  - wayland
  - unity7  
  
 openjkded:
  command: ./usr/local/JediAcademy/openjkded
  extensions: [gnome-3-38] # Required to get Glib Graphics working, see: https://www.gitmemory.com/issue/ubuntu/snapcraft-desktop-helpers/216/693388492
  plugs:
  - audio-playback
  - alsa
  - pulseaudio
  - x11
  - opengl
  - network 
  - network-bind
  
 openjk-sp:
  command: ./usr/local/JediAcademy/openjk_sp
  extensions: [gnome-3-38] # Required to get Glib Graphics working, see: https://www.gitmemory.com/issue/ubuntu/snapcraft-desktop-helpers/216/693388492
  plugs:
  - audio-playback
  - alsa
  - pulseaudio
  - x11
  - opengl
  - desktop
  - desktop-legacy
  - wayland
  - unity7
 
 openjo-sp:
  command: ./usr/local/JediOutcast/openjo_sp
  extensions: [gnome-3-38] # Required to get Glib Graphics working, see: https://www.gitmemory.com/issue/ubuntu/snapcraft-desktop-helpers/216/693388492
  plugs:
  - audio-playback
  - alsa
  - pulseaudio
  - x11
  - opengl
  - desktop
  - desktop-legacy
  - wayland
  - unity7

parts:
  openjk-bin:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/JACoders/OpenJK.git
    cmake-parameters:
    - -DBuildJK2SPEngine=ON
    - -DBuildJK2SPGame=ON
    - -DBuildJK2SPRdVanilla=ON
    after: [desktop-glib-only, patches]
    build-packages:
    - libjpeg8-dev 
    - libpng-dev 
    - zlib1g-dev 
    - libsdl2-dev
    stage-packages:
    - libfreetype6
    - libglu1-mesa
    - libopenal1
    - libsdl2-2.0-0
    - libjpeg8
    - libpng16-16
    - zlib1g
    - libpulse0
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/cmake-changes.diff
      git apply $SNAPCRAFT_STAGE/fix-debug-ifdef.diff
  patches:
    source: snap/patches
    plugin: dump
  
  desktop-glib-only:
   source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
   source-depth: 1
   source-subdir: glib-only
   plugin: make
   build-packages:
    - libglib2.0-dev
   stage-packages:
    - libglib2.0-bin
